POST http://localhost:3000/cards
Content-Type: application/json

{
  "link": "https://images.unsplash.com/photo-1690081598908-be45683775f6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwxMHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60",
  "name": "test-pic-01"
}

###
GET http://localhost:3000/cards/
Accept: application/json

###
DELETE http://localhost:3000/cards/64bfafcab615fc928ffac063
Accept: application/json

###
PUT http://localhost:3000/cards/61eade4c6d5acf558c42d9b8/likes
Accept: application/json

###

DELETE http://localhost:3000/cards/64bfafcab615fc928ffac063/likes
Accept: application/json

###