GET http://localhost:3000/users/me
Accept: application/json

###
POST http://localhost:3000/signin
Content-Type: application/json

{
  "email": "test123123@test.com",
  "password": "test123"
}

###
POST http://localhost:3000/signup
Content-Type: application/json

{
  "name": "Test",
  "email": "test@test.com",
  "password": "test123"
}

###
GET http://localhost:3000/users
Accept: application/json

###
GET http://localhost:3000/users/61eade4c6d5acf558c42d9b8
Accept: application/json

###
PATCH http://localhost:3000/users/me
Content-Type: application/json

{
  "name": "Chili-Code",
  "about": "learner"
}

###
PATCH http://localhost:3000/users/me/avatar
Content-Type: application/json

{
  "avatar": "https://images.unsplash.com/photo-1690184427947-c6cb23c64320?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwxOHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=60"
}

###